import "./globals.css";
import { Inter } from "next/font/google";
import QatatoContextProvider from "@/context/QatatoContextProvider";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "@/components/Navbar";
import Aside from "@/components/Aside";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <QatatoContextProvider>
                    <div className="min-h-screen bg-[#F7FAF9] grid grid-cols-[80px_1fr] grid-rows-[56px_1fr]">
                        <Navbar />
                        <Aside />
                        {children}
                    </div>
                </QatatoContextProvider>
            </body>
        </html>
    );
}
